### ISSUE TITLE
Step request : sort numeric

### ISSUE THREAD

**Issue by olivierodo** [restqa/restqapi#49]
**Context**

We should be able to perform assertion using. greater than, less than, equals to, not equals, etc..

**Step Proposal**

```
Then the response body at "$.foo" should be greater than
```

**Alternatives**

no

**If the Step request is approved, would you be willing to submit a PR?**

Yes

**Comment by olivierodo** [comment]
Existing : 

- Equal : `Then the response body at "id" should equal 10`

Proposal :

- Not equal: `Then the response body at "id" should not equal to 10`
- Less than: `Then the response body at "id" should be less than 10`
- Greater than : `Then the response body at "id" should be greater than 10`
- Less than or equal to : `Then the response body at "id" should be less than or equal to  10`
- Greater than or equal to : `Then the response body at "id" should be greater than or equal to 10`

**Comment by qamatters** [comment]
Thanks for taking this up.

Added some more scenarios. Let me know if it will cover them.

**Observations**: 

1. Will this comparison work for Double or float values also? As it at runtime, API usually return objects like this:

For Example: 
Id value is -> -112.5
Then the response body at "id" should be greater than -150

2. Will this comparison work for a date as a String value also?

date = "2020-12-03"
Then the response body at "date" should be less than today's date (or any custom date -> "2021-03-06" )

3. What if the id is an array of objects like below:
id = [
-150,
-210,
-100,
-112.5,
50.0,
2
]

Can I have a step like this?
3.1 -> Then each value in the response body at "id" should be greater than (less than, equals, etc) -210
3.2 -> Then the response body at "id[0]" should be greater than 10

**Providing a reference**: The above-mentioned scenario we face in our daily automation, and most of the opensource tools are not able to solve them. At that time, we have to go back to Java and start writing our own code for all these scenarios. 

https://stackoverflow.com/questions/65788369/collections-sort-method-is-throwing-class-java-lang-integer-cannot-be-cast-to-cl

In this scenario, our API was returning JSON objects for a field (for example ID) like this:

id = [
-150,
-210,
-100,
-112.5,
50.0,
2
]

And our scenarios were: 
(Filter API scenarios)

1. Each value of id should be greater than -210
2. Each value of id should be less than 100
3. Each value of id should be less than equals to 100
4. Each value of id should be greater than equals to 100
5. Each value of id should equal 10
6. There should be no empty value for each id field
7. There should be no null value for each id field

Sorting Scenarios:

1. All id field values should come in Ascending order
2. All id field values should come in descending order

Search, Filter, and Sorting is a very common requirement for APIs which deal with large data.

**Comment by olivierodo** [comment]
Thank you  @qamatters for your comment.

Regarding the different point :

1. Will be handle
2. In order to make explicit that we are performing an action on a date, this will be handle by a different step definition (proposal #54 )
3. 1/2  Will  be handled (the convention is to use JSONPATH : example: $.id.0 or $.id[0] )
4. We will need to address these step on a different issue however the approach could be different.
_Example_: Instead of using a step like `Each value of id should be greater than -210` the approach would be to relies on JSONPATH feature such as : `$.id[?(@>-210)]` that will filter the output.
So we can imagine a step like : 
```
Then the response body at "$.id[?(@>-210)]" should be equal to
"""
[
-150,
-100,
-112.5,
50.0,
2
]
```

This approach is not really user friendly.. but it allows a lot of flexibility because we can perform specific action even on nested object/array

The sort is not on the plan so far... We will need to discuss over another issue.
