### ISSUE TITLE
Translate the test scenario into a curl command

### ISSUE THREAD

**Issue by olivierodo** [restqa/restqapi#77]
Hello 👋,

### 👀 Background 

During the test scenario execution, if the user is enabling the html report he will be able to access to the detail description of the api ran behind the scene

Example:

![Screen+Recording+2564-06-27+at+02 10 51+PM](https://user-images.githubusercontent.com/4768226/123535943-a4ac2500-d751-11eb-82c2-791074596cb3.gif)

This is very helpful for the user to know more about the actual behavior of the api during the test execution, however in order to debug or to reproduce the scenario behavior it would be great to be able to run rerun the scenario manually through another tool like postman or the terminal.

### ✌️ What is the actual behavior? 

When the user is run the test, the last step will add an [attachement](https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/attachments.md) as an after hook to print the recorded apis.
File : https://github.com/restqa/restqapi/blob/master/src/restqapi/hooks.js#L52

### 🕵️‍♀️ How to reproduce the current behavior? 

1. Clone the current project: `git clone git@github.com:restqa/restqapi.git`
2. Install the dependencies: `npm i`
3. Run the command: `npm run example -- -f json:result.json`
4. Check the attachment step in the result.json

The content of the attachment step should be the detail of each api calls.

###   🤞 What is the expected behavior?

The actual behavior is good enough to know more about the api call that are executed under the scene, but in term of developer experience we should have an easy way to replicate the api call through the tool of our choice.

###   😎 Proposed solution.

The current attachment is composed of the api detail detailed composed of :
```
apis: [{
  request: {
    "hostname": "jsonplaceholder.typicode.com",
     "protocol": "https:",
     "pathname": "/todos/300000",
  },
  response: {}
}]
```

We want to propose to add the curl command of each api in the attachement:
```
apis: [{
  curl: "curl --url https://jsonplaceholder.typicode.com/todos/3000000"
  request: {
    "hostname": "jsonplaceholder.typicode.com",
     "protocol": "https:",
     "pathname": "/todos/300000",
  },
  response: {}
}]
```

Then the user will be able to copy the curl command and use it in the terminal, postman, insomnia, etc... 
This will guarantee an easy way for the user to reproduce the api call.

Cheers.

**Comment by tony-go** [comment]
Just to say that I'm on it ^^
